Repository depromeet/bboxx-iOS, pull requests merged in 2021-11, with the labels that each got.

#41 감정, 성장일기 글자 수 제한 & 데시벨 측정 결과 뷰 일러스트 추가
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage1.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage1.imageset/decibelResultImage1-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage1.imageset/decibelResultImage1-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage1.imageset/decibelResultImage1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage2.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage2.imageset/decibelResultImage2-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage2.imageset/decibelResultImage2-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage2.imageset/decibelResultImage2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage3.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage3.imageset/decibelResultImage3-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage3.imageset/decibelResultImage3-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage3.imageset/decibelResultImage3.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage4.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage4.imageset/decibelResultImage4-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage4.imageset/decibelResultImage4-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage4.imageset/decibelResultImage4.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage5.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage5.imageset/decibelResultImage5-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage5.imageset/decibelResultImage5-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage5.imageset/decibelResultImage5.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage6.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage6.imageset/decibelResultImage6-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage6.imageset/decibelResultImage6-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/decibelResultImage6.imageset/decibelResultImage6.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/stoneIcon.imageset/Mask Groupstone.1x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/stoneIcon.imageset/Mask Groupstone.2x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/stoneIcon.imageset/Mask Groupstone.3x.png
  BBOXX-iOS/BBOXX-iOS/System/BBOXX_iOSApp.swift
  BBOXX-iOS/BBOXX-iOS/Utilities/ImageAssets.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/DecibelMeasurementViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/FeelingNoteResultViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/FeelingNoteWritingViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/GrowthNote/GrowthNoteCollectionViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/GrowthNote/GrowthNoteWritingViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/Main/MainViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/DecibelMeasurementResultView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/DecibelMeasurementView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteResultView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteWritingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteCollectionView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteWritingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Intro/CreateNicknameView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Main/MainEmptySelectionView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/NotificationListView.swift
Labels: new feature

#45 성장일기 태그 선택 화면 UI 구현
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Models/Tags.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/SelectTagView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/TagCollectionView.swift
Labels: new feature

#43 감정 선택 화면 기본 UI 화면 구현
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-0.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-0.imageset/감정일기_scroll-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-0.imageset/감정일기_scroll-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-0.imageset/감정일기_scroll.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-1.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-1.imageset/감정일기_scroll-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-1.imageset/감정일기_scroll-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-1.imageset/감정일기_scroll-3.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-10.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-10.imageset/감정일기_scroll-10.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-10.imageset/감정일기_scroll-11.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-10.imageset/감정일기_scroll-12.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-11.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-11.imageset/감정일기_scroll-11.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-11.imageset/감정일기_scroll-12.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-11.imageset/감정일기_scroll-13.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-12.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-12.imageset/감정일기_scroll-12.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-12.imageset/감정일기_scroll-13.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-12.imageset/감정일기_scroll-14.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-2.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-2.imageset/감정일기_scroll-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-2.imageset/감정일기_scroll-3.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-2.imageset/감정일기_scroll-4.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-3.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-3.imageset/감정일기_scroll-3.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-3.imageset/감정일기_scroll-4.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-3.imageset/감정일기_scroll-5.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-4.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-4.imageset/감정일기_scroll-4.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-4.imageset/감정일기_scroll-5.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-4.imageset/감정일기_scroll-6.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-5.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-5.imageset/감정일기_scroll-5.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-5.imageset/감정일기_scroll-6.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-5.imageset/감정일기_scroll-7.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-6.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-6.imageset/감정일기_scroll-6.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-6.imageset/감정일기_scroll-7.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-6.imageset/감정일기_scroll-8.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-7.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-7.imageset/감정일기_scroll-7.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-7.imageset/감정일기_scroll-8.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-7.imageset/감정일기_scroll-9.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-8.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-8.imageset/감정일기_scroll-10.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-8.imageset/감정일기_scroll-8.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-8.imageset/감정일기_scroll-9.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-9.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-9.imageset/감정일기_scroll-10.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-9.imageset/감정일기_scroll-11.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/감정일기_scroll-9.imageset/감정일기_scroll-9.png
  BBOXX-iOS/BBOXX-iOS/Extensions/Image+Extension.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/SelectFeelingViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingButton.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectFeelingView.swift
Labels: new feature

#47 감정일기 카테고리 선택 화면 UI 및 기본 기능 구현
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/d.colorset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/disabledButtonColor.colorset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Group 376-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Group 376-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Group 376.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_pickView.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_pickView.imageset/small.png
  BBOXX-iOS/BBOXX-iOS/Utilities/ImageAssets.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectCategoryView.swift
Labels: new feature

#52 감정일기 카테고리 선택 화면 UI 디테일 구현
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectCategoryView.swift
Labels: new feature, details

#51 메인 화면 리팩토링
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_background.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_background.imageset/Group 348-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_background.imageset/Group 348-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_background.imageset/Group 348.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_button_background_color.colorset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Utilities/ImageAssets.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Main/MainView.swift
Labels: refactor

#53 메인-비우기 선택 뷰 수정 & 타임머신(알림) 네트워크 연결
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_backButton.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_backButton.imageset/left-large-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_backButton.imageset/left-large-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_backButton.imageset/left-large.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_feelingNote.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_feelingNote.imageset/Group 248-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_feelingNote.imageset/Group 248-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_feelingNote.imageset/Group 248.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_feelingNote.imageset/main_empty_selection_feelingNote.1x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_feelingNote.imageset/main_empty_selection_feelingNote.2x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_feelingNote.imageset/main_empty_selection_feelingNote.3x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_full_background.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_full_background.imageset/Group 361-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_full_background.imageset/Group 361-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_full_background.imageset/Group 361.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_shouting.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_shouting.imageset/Group 247-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_shouting.imageset/Group 247-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_shouting.imageset/Group 247.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_shouting.imageset/main_empty_selection_shouting.1x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_shouting.imageset/main_empty_selection_shouting.2x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_empty_selection_shouting.imageset/main_empty_selection_shouting.3x.png
  BBOXX-iOS/BBOXX-iOS/Models/Notification.swift
  BBOXX-iOS/BBOXX-iOS/Models/NotificationResponse.swift
  BBOXX-iOS/BBOXX-iOS/Networks/FeelingNoteService.swift
  BBOXX-iOS/BBOXX-iOS/Networks/NotificationService.swift
  BBOXX-iOS/BBOXX-iOS/Utilities/ImageAssets.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/GrowthNote/GrowthNoteCollectionViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/NotificationListViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectFeelingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteCell.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteCollectionView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Intro/SignInView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Main/MainEmptySelectionView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/NotificationListView.swift
Labels: new feature, refactor

#55 뷰 디테일 작업 & 감정일기 삭제 네트워크 연결
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/TimeMachineIcon.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/TimeMachineIcon.imageset/diary-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/TimeMachineIcon.imageset/diary-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/TimeMachineIcon.imageset/diary.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/TimeMachineIcon.imageset/timeMachineIcon.1x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/TimeMachineIcon.imageset/timeMachineIcon.2x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/TimeMachineIcon.imageset/timeMachineIcon.3x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/d.colorset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/emptyingIcon.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/emptyingIcon.imageset/emotion-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/emptyingIcon.imageset/emotion-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/emptyingIcon.imageset/emotion.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/emptyingIcon.imageset/emptyingIcon.1x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/emptyingIcon.imageset/emptyingIcon.2x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/emptyingIcon.imageset/emptyingIcon.3x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_down.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_down.imageset/down-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_down.imageset/down-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_down.imageset/down.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_down.imageset/main_down.1x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_down.imageset/main_down.2x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/main_down.imageset/main_down.3x.png
  BBOXX-iOS/BBOXX-iOS/Models/GrowthNoteResponse.swift
  BBOXX-iOS/BBOXX-iOS/Networks/FeelingNoteService.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/FeelingNoteReviewViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/NotificationListViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteReviewView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteCell.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteCollectionView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteDetailView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Main/MainView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/NotificationCell.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/NotificationListView.swift
Labels: refactor

#58 성장일기 태그 뷰 레이아웃 변경 및 성장일기 작성 네트워크 연결
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteReviewView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/SelectTagView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/TagCollectionView.swift
Labels: refactor

#61 감정 선택 뷰 레이아웃 조정
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Models/Tags.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/SelectFeelingViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/GrowthNote/SelectTagViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingButton.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectCategoryView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectFeelingView.swift
Labels: refactor

#62 감정일기 작성 네트워크 연결 리팩토링
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Group 376-1.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Group 376-2.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/Group 376.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/select_category_image.1x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/select_category_image.2x.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/select_category_image.imageset/select_category_image.3x.png
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/FeelingNoteRemindViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/FeelingNoteWritingViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/SelectCategoryViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/FeelingNote/SelectFeelingViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/GrowthNote/GrowthNoteWritingViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingButton.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteRemindView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteResultView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteWritingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectCategoryView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectFeelingView.swift
Labels: refactor, details

#60 Push Notification 권한 요청 및 애플 로그인
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/BBOXX-iOS.entitlements
  BBOXX-iOS/BBOXX-iOS/Helpers/SignIn/AppleSignInCoordinator.swift
  BBOXX-iOS/BBOXX-iOS/System/SystemPermissionChecker.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Intro/SplashView.swift
Labels: new feature

#75 다크모드 시, 색상 반전되는 이슈 & 소리치기 결과 뷰 관련 이슈 수정
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Extensions/UserDefaults+Extension.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/BottomCard.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/CustomTextField.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/DecibelMeasurementResultViewModel.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/DecibelMeasurementViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/DecibelMeasurementResultView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/DecibelMeasurementView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteResultView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteWritingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectFeelingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteWritingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/Intro/CreateNicknameView.swift
Labels: bug, refactor, QA

#76 성장일기에서 감정일기 보기 구현 및 성장일기/감정일기 화면 관련 수정
  BBOXX-iOS/BBOXX-iOS.xcodeproj/project.pbxproj
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/downButton.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/downButton.imageset/down.png
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/upButton.imageset/Contents.json
  BBOXX-iOS/BBOXX-iOS/Assets.xcassets/upButton.imageset/up-1.png
  BBOXX-iOS/BBOXX-iOS/Extensions/View+Extension.swift
  BBOXX-iOS/BBOXX-iOS/Utilities/ImageAssets.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/BottomCard.swift
  BBOXX-iOS/BBOXX-iOS/ViewModels/GrowthNote/GrowthNoteDetailContentViewModel.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/FeelingNoteWritingView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/FeelingNote/SelectCategoryView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteCollectionView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteDetailContentView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteDetailView.swift
  BBOXX-iOS/BBOXX-iOS/Views/Scenes/GrowthNote/GrowthNoteWritingView.swift
Labels: bug, new feature, QA
